metadata:
  name: 吴天
  phone: (+86) 133-****-****
  email: me@skywt.cn
  photo: /photo.jpg
objects:
  schools:
    - slug: hnu
      name: 湖南大学
      college: 信息科学与工程学院
      major: 信息安全专业
      degree: 本科（在读）
      date: 2021 年 9 月 - 2025 年 6 月
      majorCourses: 程序设计、算法与数据结构、体系结构、操作系统、数据库系统、计算机网络、网络安全等
      score: GPA 3.61/4.00，专业排名 21%
    - slug: hnu-en
      name: Hunan University
      # college: College of Computer Science and Electronic Engineering
      major: Bachelor of Information Security
      degree: Undergraduate
      date: Sept. 2021 - Jun. 2025 (expected)
      majorCourses: Programming, Algorithms and Data Structures, Computer
        Architecture, Operating Systems, Database Systems, Computer
        Networks, Compilers
      score: 3.6/4.0, (Ranked in the top 21%)
  projects:
    - slug: hnu-wei-life
      title: 湖大微生活小程序
      type: <i class="ti ti-users"></i> 团队项目
      job: 前端开发
      date: 2022 年 3 月 - 2023 年 10 月
      # tech: React.js, Taro.js, 微信小程序, TypeScript,
      desc: 为湖南大学同学提供课表查看、成绩查询等功能的小程序，同时兼容微信、QQ 小程序平台。学生社团产品。
      items:
        - <b>技术栈：<i class="ti ti-brand-react"></i> React.js / <i class="ti ti-layers-intersect"></i> Taro.js / <i class="ti ti-brand-miniprogram"></i> 微信小程序 / <i class="ti ti-brand-typescript"></i> TypeScript</b>。
        - 参与团队需求评审会议确定新增功能，讨论制定相关 API 标准并编写相关文档。
        - 基于 Taro.js 和 React.js 框架，开发并测试部分前端页面和模块，构建跨端小程序。
        - 共开发 5 个页面，实现了工具箱、问题反馈等多个功能，项目上线后稳定运行。
    - slug: hnu-wei-life-en
      title: HNU Wei Life
      type: Team Project
      job: Frontend, O&M
      date: Mar. 2023 - Oct. 2023
      tech: React.js, Taro.js, TypeScript, WeChat Mini Program
      desc: A WeChat Mini Program designed for HNU students,
        providing features such as class schedule view and score query.
      items:
        - Actively participated in project planning meetings to identify and propose new features.
        - Established <b>API standards</b> and authored <b>API documentation</b>.
        - <b>Developed frontend modules</b> using React.js and Taro frameworks.
        - Ensured the stability of the product since its update.
    - slug: lib-backend
      title: 易千图书管理系统
      type: <i class="ti ti-users"></i> 团队项目
      job: 后端开发
      date: 2022 年 2 月 - 2022 年 3 月
      # tech: Python, Flask, MySQL
      desc: 功能齐全的前后端分离图书管理系统，实现了图书借阅、书籍信息管理、用户注册登录等多种功能。
      items:
        - <b>技术栈：<i class="ti ti-brand-python"></i> Python / <i class="ti ti-pepper"></i> Flask / <i class="ti ti-brand-mysql"></i> MySQL</b>。
        - 负责共同制定 RESTful API 标准及编写相关文档。
        - 负责系统后端开发，使用 Python Flask 作为 Web 框架，使用 SQLAlchemy ORM 模块操作 MySQL 数据库，使用 JWT 实现管理用户登录状态。
        - 共实现 18 个接口，共使用 3 张数据表。
    - slug: lib-backend-en
      title: Library Management System
      type: Team Project
      job: Backend
      date: Feb. 2022 - Mar. 2022
      tech: Python, Flask, MySQL
      desc: A comprehensive library management system.
      items:
        - Contributed to the software's <b>architecture design</b> by collaborating with team members
          to determine data storage and API interfaces.
        - Authored the <b>API documentation</b>.
        - <b>Developed the backend</b> using Python Flask framwork.
    - slug: skywt-cn
      title: 博客系统 Daydreamer
      type: <i class="ti ti-user"></i> 个人项目
      date: 2023 年 10 月 - 2024 年 3 月
      # tech: Astro.js, React.js, TypeScript, Tailwind.css, Docker
      desc: 基于 Typecho 的博客系统前端。
      items:
        - <b>技术栈：<i class="ti ti-brand-astro"></i> Astro.js / <i class="ti ti-brand-react"></i> React.js / <i class="ti ti-brand-nodejs"></i> Node.js / <i class="ti ti-brand-javascript"></i> JavaScript / <i class="ti ti-brand-tailwind"></i> Tailwind</b>。
        - 基于 Typecho 提供的 RESTful API，设计并开发博客系统前端。
        - 部署在个人博客 skywt.cn，使用 GitHub Actions 进行自动化部署。
    - slug: skywt-cn-en
      title: Website & Blog skywt.cn
      type: Personal Project
      date: Nov. 2017 - Present
      tech: Astro.js, React.js, TypeScript, Tailwind.css, CSS, Docker
      desc: A personal website showcasing my work and interests.
      items:
        - Maintained the website for six years, publishing over a hundred articles.
        - Regularly developed new versions using the latest technologies.
          The most recent version was built with <b>Astro.js</b>, <b>TypeScript</b>, and <b>Tailwind.css</b>.
        - <b>Self-hosted</b> numerous open-source services on the server.
    - slug: daydream
      title: Typecho 博客主题 Daydream
      type: 个人项目
      date: 2022 年 3 月 - 2022 年 10 月
      tech: JavaScript, jQuery, AJAX, PHP, CSS
      desc: 针对 Typecho 博客系统开发的一套博客主题，集成多种功能。
      items:
        - 独立设计主题外观，使用 pico.css 组件库实现网页效果。
        - 使用 PHP 进行代码实现。
        - 在 <i class="ri-github-line"></i> GitHub 开源并获得 70 star。
    - slug: daydream-en
      title: Daydream
      type: Personal Project
      date: Mar. 2022 - Oct. 2022
      tech: JavaScript, jQuery, AJAX, PHP, CSS
      desc: A feature-rich blog theme for the Typecho blog system.
      items:
        - Independently designed the theme's appearance, utilizing the pico.css component library.
        - Implemented the theme using <b>PHP</b>.
        - Open source on <i class="ri-github-line"></i> <b>GitHub</b> and received 68 starts.
    - slug: calmlock
      title: Calm Lock App
      type: 个人项目
      date: 2024 年 2 月
      tech: Swift, SwiftUI, iOS, macOS
      desc: 需要等待设定时间才能解锁查看存储内容的 iOS / macOS 软件。Apple Swift Student Challenge 2024 参赛作品。
      items:
        - 独立设计 UI / UX，并使用 Swift 和 SwiftUI 进行代码实现。
        - 从初次接触 Swift、SwiftUI 到开发完成整个 App，仅用时 5 天时间。
    - slug: calmlock-en
      title: Calm Lock
      type: Personal Project
      date: "2024"
      tech: Swift, SwiftUI, iOS, macOS
      desc: iOS/macOS software that requires a set time to unlock to view stored content.
      items:
        - Designed and implemented the user interface (UI) and user experience (UX) of the application independently.
        - Developed the application using <b>Swift and SwiftUI</b>, leveraging their capabilities to create a seamless and intuitive user interface.
        - Achieved a rapid development timeline, completing the entire project <b>within just 5 days</b> from initial contact with Swift and SwiftUI.
    - slug: qnxg-people
      title: 易千人员管理系统
      type: 团队项目
      job: 后端
      date: 2023 年
      tech: Go, Gin, MySQL
      desc: 用于湖南大学“易千网络文化工作室”人员管理。
      items:
        - 参与设计软件架构，与团队成员讨论确定数据存储、API 接口等。
        - 参与系统后端开发，使用 Go Gin 框架在后端对 API 进行实现。
    - slug: qnxg-people-en
      title: QNXG Staff Management System
      type: Team Project
      job: Backend
      date: "2023"
      tech: Go, Gin, MySQL
      desc: Used for the staff management of QNXG Network Culture Studio of HNU.
    - slug: pasteburn
      title: PasteBurn 阅后即焚
      type: 个人项目
      date: 2019 年
      tech: jQuery, CSS, PHP, MySQL
      desc: 支持分享文本，阅后即焚的网页程序。高中课余时间开发。
      items:
        - 独立设计并使用 PHP 开发了网站的功能，使用 Bootstrap4 进行页面设计，使用 jQuery、AJAX 等实现前端逻辑，后端使用 MySQL 数据库进行存储。
        - 在 <i class="ri-github-line"></i> GitHub 开源并获得 26 star。
    - slug: pasteburn-en
      title: PasteBurn
      type: Personal Project
      date: "2019"
      tech: jQuery, CSS, PHP, MySQL
      desc: Support for sharing text, burn after reading web application. High school spare time development.
    - slug: vuecho
      title: Vuecho 博客系统
      type: 个人项目
      date: 2022 年
      tech: Vue.js, JavaScript, Tailwind.css, CSS
      desc: 基于 Vue.js 构建的博客前端，使用 Typecho 博客系统提供的 API。
      items:
        - 根据 Typecho RestFul APi 插件提供的 API 标准，使用 Vue.js 构建了前端页面。
        - 使用 axios 进行数据请求，使用 vue-router 进行路由管理。
        - 基于 Tailwind.css 进行网页设计。
    - slug: vuecho-en
      title: Vuecho Blog System
      type: Personal Project
      date: "2022"
      tech: Vue.js, JavaScript, Tailwind.css, CSS
      desc: Blog system frontend based on Vue.js, using API provided by Typecho.
    - slug: webcv
      title: WebCV 简历系统
      type: 个人项目
      date: 2024 年
      tech: Astro.js, TypeScript, Tailwind.css, CSS
      desc: 基于 Astro.js 的网页简历生成管理系统。
    - slug: webcv-en
      title: WebCV Resume System
      type: Personal Project
      date: "2024"
      tech: Astro.js, TypeScript, Tailwind.css, CSS
      desc: CV generation tool based on Astro.js.
  items:
    - slug: ccpc
      title: 中国大学生程序设计竞赛（CCPC）广州站
      subtitle: 银奖
      date: 2021 年 11 月
    - slug: ccpc-en
      title: China Collegiate Programming Contest (CCPC) Guangzhou
      subtitle: silver award
      date: Nov. 2021
    - slug: csp
      title: CCF 计算机软件能力认证（CSP）
      date: 2022 年 9 月
      subtitle: 290 分，全国排名 4.6%
    - slug: csp-en
      title: CCF Certified Software Professional (CSP)
      subtitle: 290/500, National Ranking 4.6%
      date: Sept. 2022
    - slug: csp-s
      title: CCF 非专业级软件能力认证提高组（CSP-S）
      subtitle: 一等奖
      date: 2019 年 11 月
      note: 2019 年，由于政策原因，CCF 以 CSP-S 的名义举办了全国青少年信息学奥林匹克联赛（NOIP）。因故， CSP-S 一等奖等同于 NOIP 提高组复赛一等奖。
    - slug: csp-s-en
      title: CCF Unprofessional Certified Software Professional (CSP-S)
      subtitle: first prize
      date: Nov. 2019
      note: "Note: In 2019, for policy reasons, CCF organized the National Olympiad in Informatics in Provinces (NOIP) under the name CSP-S. Therefore, the first prize of CSP-S is equivalent to the first prize of the NOIP."
    - slug: noip
      title: 全国青少年信息学奥林匹克联赛（NOIP）
      subtitle: 一等奖
      date: 2019 年 11 月
    - slug: noip-en
      title: National Information Security Test Program (NISP)
      subtitle: Level 1
      date: May. 2023
    - slug: cet6
      title: 大学英语六级考试（CET6）
      date: 2023 年 3 月
      subtitle: 566 分
    - slug: cet6-en
      title: College English Test Level 6 (CET6)
      subtitle: 566/710
      date: Mar. 2023
    - slug: nisp
      title: 国家信息安全水平证书（NISP）
      date: 2023 年 5 月
      subtitle: 一级
    - slug: nisp-en
      title: National Information Security Test Program
      date: May. 2023
      subtitle: Level 1
    - slug: hnu-ctf
      title: 湖南大学第二届信息安全夺旗赛（CTF）校赛
      subtitle: 第二名
      date: 2022 年 10 月
    - slug: hnu-ctf-en
      title: The second Information Security Capture the Flag Competition (CTF) of HNU
      subtitle: proxime accessit
      date: Oct. 2022
    - slug: greatwall
      title: “长城杯”第四届信息安全铁人三项赛（分区赛）
      subtitle: 二等奖
      date: 2023 年 5 月
    - slug: math-model
      title: 全国大学生数学建模竞赛（湖南赛区）
      subtitle: 二等奖
      date: 2023 年
    - slug: math-model-en
      title: National College Students Mathematical Contest in Modeling, Hunan area
      subtitle: second prize
      date: "2023"
    - slug: hnu-meric
      title: 湖南大学校级三好学生
      date: 2022 年
    - slug: hnu-meric-en
      title: Merit Student of HNU
      date: "2022"
    - slug: scholarship
      title: 湖南大学二等综合奖学金、单项奖学金
      date: 2022 年、2023 年
    - slug: scholarship-en
      title: Second Class Comprehensive Scholarship, Individual Scholarship of HNU
      date: 2022, 2023
    - slug: hnusec
      title: 湖南大学信息安全协会（HNUSec）
      subtitle: 会长
      date: 2023 年 9 月至今
    - slug: hnusec-en
      title: Information Security Association of HNU (HNUSec)
      subtitle: President
      date: Sept. 2023 - now
    - slug: chuanglian
      title: 湖南大学创联学生实验室（前微软俱乐部）
      subtitle: 主席
      date: 2023 年 9 月至今
    - slug: chuanglian-en
      title: Chuanglian Student Lab (former Microsoft Club)
      subtitle: President
      date: Sept. 2023 - now
    - slug: debate-team
      title: 湖南大学信息科学与工程学院辩论队
      subtitle: 队长
      date: 2022 年 7 月 - 2023 年 7 月
    - slug: debate-team-en
      title: Debate Team of HNU CSEE
      subtitle: Captain
      date: Jul. 2022 - Jul. 2023
    - slug: orientation-team
      title: 湖南大学信息科学与工程学院 2023 年迎新团队
      subtitle: 新生班导
      date: 2023 年 9 月
    - slug: orientation-team-en
      title: HNU CSEE 2023 Orientation Team
      subtitle: Member
      date: Sept. 2023
  bullets:
    - slug: languages
      content: "<b>语言：<i class='ti ti-brand-cpp'></i> C++ / <i class='ti ti-brand-javascript'></i> JavaScript / <i class='ti ti-brand-typescript'></i> TypeScript / <i class='ti ti-brand-html5'></i> HTML5 / <i class='ti ti-brand-css3'></i> CSS3 / <i class='ti ti-brand-python'></i> Python / <i class='ti ti-brand-swift'></i> Swift / <i class='ti ti-brand-php'></i> PHP</b>"
    - slug: languages-en
      content: "<b>Languages</b>: C++, JavaScript, TypeScript, HTML/CSS, Python, Swift, PHP"
    - slug: frameworks
      content: "<b>框架：<i class='ti ti-brand-react'></i> React.js / <i class='ti ti-brand-vue'></i> Vue.js / <i class='ti ti-brand-astro'></i> Astro.js / <i class='ti ti-file-type-js'></i> jQuery / <i class='ti ti-brand-tailwind'></i> Tailwind.css / <i class='ti ti-pepper'></i> Python Flask / <i class='ti ti-brand-swift'></i> SwiftUI</b>"
    - slug: frameworks-en
      content: "<b>Framworks</b>: React.js, Vue.js, Astro.js、jQuery, Tailwind.css、Python Flask、SwiftUI"
    - slug: coding
      content: "<b>编程</b>：面向对象编程、算法与数据结构"
    - slug: coding-en
      content: "<b>Programming</b>: Object-Oriented Programming, Algorithms and Data Structures"
    - slug: techs
      content: "<b>技术：<i class='ti ti-terminal-2'></i> Linux / <i class='ti ti-brand-git'></i> Git / <i class='ti ti-brand-openai'></i> ChatGPT / <i class='ti ti-brand-github-copilot'></i> Copilot / <i class='ti ti-brand-docker'></i> Docker</b>"
    - slug: techs-en
      content: "<b>Techs</b>: Linux, Git, ChatGPT, Docker"
    - slug: soft-skills
      content: "<b>软技能</b>：高效沟通、领导力、团队协作"
    - slug: soft-skills-en
      content: "<b>Soft Skills</b>: Effective Communication, Leadership, Teamwork"
    - slug: study-quickly
      content: 具备<b>快速学习新技术和工具</b>的能力，对技术充满热情，学习适应能力强，喜欢深入研究。
    - slug: study-quickly-en
      content: I have a strong <b>aptitude for learning</b> and can quickly grasp and apply new technologies and tools. I am passionate about technology and enjoy delving into its intricacies.
    - slug: algorithm-foundation
      content: 在多年的算法竞赛训练中，建立了<b>扎实的算法基础</b>，对算法与数据结构应用有深入理解和灵活的思维。
    - slug: algorithm-foundation-en
      content: I possess a solid fundation in <b>algorithms</b> due to years of training in algorithmic competitions. This has provided me with a deep understanding of applying algorithms and data structures, as well as fostering adaptable thinking.
    - slug: good-taste
      content: 具备良好的<b>技术品味</b>，注重代码质量和系统设计的简洁性等方面。
    - slug: good-taste-en
      content: I have a strong <b>appreciation</b> for technical excellence and <b>a commitment to code quality and elegant system design</b>.
    - slug: good-aesthetic
      content: 具备良好的<b>视觉审美</b>，对产品的用户体验有自己的见解。
    - slug: product-sense
      content: 具备良好的<b>产品品味</b>，乐于构建优良的产品用户体验，而非机械地完成任务。
    - slug: good-communication
      content: 拥有<b>出色的沟通和人际交往能力和强烈的责任心</b>，曾担任社团主席，积累了一定的领导经验。
    - slug: good-communication-en
      content: I excel in <b>communication and interpersonal skills</b> and have demonstrated leadership abilities as the president of student organizations. I am adept at fostering teamwork and effectively collaborating with team members.
    - slug: tencent
      content: <b>认同腾讯公司的文化与愿景</b>，希望创造出色的产品和体验。
    - slug: meituan
      content: <b>认同美团的文化与愿景</b>，希望参与创造出色的「科技+零售」体验。
    - slug: bytedance
      content: <b>认同字节跳动的文化与愿景</b>，希望创造出色的产品和体验。
    - slug: jd
      content: <b>认同京东的文化与愿景</b>，希望参与创造出色的零售科技体验。
    - slug: xhs
      content: <b>认同小红书的文化与愿景</b>，希望参与创造出色的年轻人生活平台。
    - slug: netease
      content: <b>认同网易的文化与愿景</b>，希望创造出色的产品和体验。
    - slug: bilibili
      content: <b>认同哔哩哔哩的文化与愿景</b>，希望通过出色的产品和体验，为年轻人打造快乐的平台。
    - slug: xiaomi
      content: <b>认同小米的文化与愿景</b>，希望创造出色的产品体验。
    - slug: dingtalk
      content: <b>认同钉钉产品的使命、文化和愿景</b>，希望打造出色的智能办公协作体验。
    - slug: aliyun
      content: <b>认同阿里云的文化与愿景</b>，希望参与创造出色的云体验。
    - slug: microsoft
      content: I wholeheartedly embrace <b>Microsoft's culture, values, and commitment to innovation</b>, and I am excited to contribute my skills and passion to its dynamic environment.
    - slug: apple
      content: I am inspired by <b>Apple's values</b> and admire their exceptional product design. I hold deep admiration for Apple's ability to drive human progress through their innovative products, and I am eager to contribute to this mission through an internship.
